# Generated by Django 6.0.1 on 2026-01-20 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Név')),
                ('short_name', models.CharField(max_length=20, verbose_name='Rövid név')),
            ],
            options={
                'verbose_name': 'Bajnokság',
                'verbose_name_plural': 'Bajnokságok',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Név')),
                ('start_date', models.DateField(verbose_name='Kezdete')),
                ('end_date', models.DateField(verbose_name='Vége')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
            ],
            options={
                'verbose_name': 'Szezon',
                'verbose_name_plural': 'Szezonok',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Név')),
                ('short_name', models.CharField(blank=True, max_length=50, verbose_name='Rövid név')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Város')),
            ],
            options={
                'verbose_name': 'Csapat',
                'verbose_name_plural': 'Csapatok',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Név')),
                ('city', models.CharField(max_length=100, verbose_name='Város')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Cím')),
            ],
            options={
                'verbose_name': 'Helyszín',
                'verbose_name_plural': 'Helyszínek',
                'ordering': ['city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Név')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='matches.competition', verbose_name='Bajnokság')),
            ],
            options={
                'verbose_name': 'Szakasz',
                'verbose_name_plural': 'Szakaszok',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Dátum')),
                ('time', models.TimeField(verbose_name='Időpont')),
                ('court', models.CharField(blank=True, max_length=50, verbose_name='Pálya')),
                ('status', models.CharField(choices=[('scheduled', 'Kiírva'), ('confirmed', 'Visszaigazolva'), ('completed', 'Lejátszva'), ('cancelled', 'Törölve')], default='scheduled', max_length=20, verbose_name='Státusz')),
                ('notes', models.TextField(blank=True, verbose_name='Megjegyzés')),
                ('external_id', models.CharField(blank=True, max_length=100, verbose_name='Külső azonosító')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='matches.competitionphase', verbose_name='Szakasz')),
                ('away_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_matches', to='matches.team', verbose_name='Vendég csapat')),
                ('home_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_matches', to='matches.team', verbose_name='Hazai csapat')),
                ('venue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='matches.venue', verbose_name='Helyszín')),
            ],
            options={
                'verbose_name': 'Mérkőzés',
                'verbose_name_plural': 'Mérkőzések',
                'ordering': ['date', 'time'],
            },
        ),
        migrations.AddField(
            model_name='competition',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='matches.season', verbose_name='Szezon'),
        ),
        migrations.CreateModel(
            name='MatchAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('referee', 'Játékvezető'), ('inspector', 'Ellenőr'), ('reserve', 'Tartalék')], default='referee', max_length=20, verbose_name='Szerep')),
                ('response_status', models.CharField(choices=[('pending', 'Függőben'), ('accepted', 'Elfogadva'), ('declined', 'Elutasítva')], default='pending', max_length=20, verbose_name='Válasz')),
                ('response_date', models.DateTimeField(blank=True, null=True, verbose_name='Válasz dátuma')),
                ('decline_reason', models.CharField(blank=True, max_length=300, verbose_name='Elutasítás indoka')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='matches.match', verbose_name='Mérkőzés')),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='referees.referee', verbose_name='Játékvezető')),
            ],
            options={
                'verbose_name': 'Kijelölés',
                'verbose_name_plural': 'Kijelölések',
                'unique_together': {('match', 'referee')},
            },
        ),
    ]
