# Generated by Django 5.1.5 on 2026-01-21 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_update_matchassignment_and_match'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktív'),
        ),
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='team_logos/', verbose_name='Logó'),
        ),
        migrations.AddField(
            model_name='venue',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktív'),
        ),
        migrations.AlterField(
            model_name='match',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_matches', to=settings.AUTH_USER_MODEL, verbose_name='Létrehozta'),
        ),
        migrations.AlterField(
            model_name='match',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='matches.venue', verbose_name='Helyszín'),
        ),
        migrations.CreateModel(
            name='TeamAlternativeName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Alternatív név')),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matches.competition', verbose_name='Bajnokság (opcionális)')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_names', to='matches.team', verbose_name='Csapat')),
            ],
            options={
                'verbose_name': 'Alternatív csapatnév',
                'verbose_name_plural': 'Alternatív csapatnevek',
            },
        ),
    ]
