# Generated by Django 5.1.5 on 2026-01-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_add_team_venue_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='color',
            field=models.CharField(default='#6366f1', help_text='Hex színkód (pl. #6366f1)', max_length=7, verbose_name='Szín'),
        ),
    ]
