# Generated by Django 5.1.5 on 2026-01-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_add_competition_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionphase',
            name='payment_amount',
            field=models.PositiveIntegerField(default=0, help_text='Mérkőzésenkénti díjazás forintban', verbose_name='Díjazás (Ft)'),
        ),
        migrations.AddField(
            model_name='competitionphase',
            name='payment_type',
            field=models.CharField(choices=[('per_person', 'Fő / mérkőzés'), ('total', 'Összesen / mérkőzés')], default='per_person', max_length=20, verbose_name='Díjazás típusa'),
        ),
    ]
