# Generated by Django 5.1.5 on 2026-01-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_add_phase_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Név')),
                ('color', models.CharField(help_text='Hex színkód', max_length=7, verbose_name='Szín')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sorrend')),
            ],
            options={
                'verbose_name': 'Mentett szín',
                'verbose_name_plural': 'Mentett színek',
                'ordering': ['order', 'name'],
            },
        ),
    ]
