# Generated by Django 5.1.5 on 2026-01-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_add_saved_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionphase',
            name='inspector_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Ellenőrök száma'),
        ),
        migrations.AddField(
            model_name='competitionphase',
            name='referee_count',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Játékvezetők száma'),
        ),
        migrations.AddField(
            model_name='competitionphase',
            name='reserve_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Tartalékok száma'),
        ),
    ]
