# Generated by Django 5.1.5 on 2026-01-21 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_add_phase_composition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matchassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='matchassignment',
            name='placeholder_type',
            field=models.CharField(blank=True, choices=[('', '-'), ('hianyzik', 'Hiányzik!'), ('szukseges', 'Szükséges'), ('nincs', 'Nincs')], default='', max_length=20, verbose_name='Helykitöltő típus'),
        ),
        migrations.AlterField(
            model_name='matchassignment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Játékvezető'),
        ),
    ]
