# Generated by Django 5.1.5 on 2026-01-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_add_placeholder_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchassignment',
            name='role',
            field=models.CharField(choices=[('referee', 'Játékvezető'), ('reserve', 'Tartalék'), ('inspector', 'Ellenőr'), ('tournament_director', 'Tornaigazgató')], default='referee', max_length=20, verbose_name='Szerep'),
        ),
    ]
