# Generated by Django 5.1.5 on 2026-01-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_add_tournament_director_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_assignment_published',
            field=models.BooleanField(default=True, help_text='Ha nincs bejelölve, a kiírás nem jelenik meg (Még nincs kiírás)', verbose_name='Kiírás publikálva'),
        ),
        migrations.AddField(
            model_name='match',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Ha be van jelölve, a mérkőzés csak a kiírások oldalon látható', verbose_name='Rejtett'),
        ),
    ]
