# Generated by Django 5.1.5 on 2026-01-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0010_add_match_visibility_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Dátum'),
        ),
        migrations.AlterField(
            model_name='match',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Időpont'),
        ),
    ]
