# Generated by Django 5.1.5 on 2026-01-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0011_make_date_time_optional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-is_tbd', 'name'], 'verbose_name': 'Csapat', 'verbose_name_plural': 'Csapatok'},
        ),
        migrations.AddField(
            model_name='team',
            name='is_tbd',
            field=models.BooleanField(default=False, help_text='Ha be van jelölve, ez a csapat a "Még nem ismert" helyőrző', verbose_name='TBD csapat'),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('created', 'Létrehozott'), ('draft', 'Piszkozat'), ('incomplete', 'Hiányos'), ('scheduled', 'Kiírt'), ('confirmed', 'Megerősített'), ('postponed', 'Halasztott'), ('cancelled', 'Törölt')], default='draft', max_length=20, verbose_name='Státusz'),
        ),
    ]
