# Generated by Django 5.1.5 on 2026-01-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0012_add_team_is_tbd'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Törlés időpontja'),
        ),
        migrations.AddField(
            model_name='match',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Ha be van jelölve, a mérkőzés nem jelenik meg sehol (soft delete)', verbose_name='Törölve'),
        ),
        migrations.AlterField(
            model_name='match',
            name='is_assignment_published',
            field=models.BooleanField(default=False, help_text='Ha nincs bejelölve, a kiírás nem jelenik meg (Még nincs kiírás)', verbose_name='Kiírás publikálva'),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('draft', 'Piszkozat'), ('created', 'Létrehozott'), ('scheduled', 'Kiírt'), ('confirmed', 'Megerősített'), ('postponed', 'Halasztott'), ('cancelled', 'Elmarad')], default='draft', max_length=20, verbose_name='Státusz'),
        ),
    ]
