# Generated by Django 5.1.5 on 2026-01-28 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0014_add_tournament_and_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='tournament_court_count',
            field=models.PositiveIntegerField(default=1, help_text='Tornánál: hány pályán játszanak egyszerre (= játékvezetők száma)', verbose_name='Pályák száma'),
        ),
    ]
