# Generated by Django 5.1.5 on 2026-01-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0015_add_tournament_court_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionphase',
            name='requires_mfsz_declaration',
            field=models.BooleanField(default=True, help_text='Ha be van jelölve, a könyvelő értesítést kap a mérkőzésekről', verbose_name='MFSZ bejelentés szükséges'),
        ),
        migrations.AddField(
            model_name='match',
            name='mfsz_declaration_override',
            field=models.BooleanField(blank=True, default=None, help_text='None: szakasz beállítás, True: kötelező bejelentés, False: nem kell bejelentés', null=True, verbose_name='MFSZ bejelentés felülírás'),
        ),
    ]
