# Generated by Django 6.0.1 on 2026-01-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0016_add_mfsz_declaration_and_gross'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='google_maps_url',
            field=models.URLField(blank=True, help_text='A helyszín Google Maps linkje (pl. https://maps.google.com/...)', max_length=500, verbose_name='Google Maps link'),
        ),
    ]
