# Generated by Django 5.1.5 on 2026-01-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0017_add_venue_google_maps_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Irányítószám'),
        ),
    ]
