# Generated by Django 6.0.1 on 2026-01-29 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0018_add_venue_postal_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionphase',
            name='inspector_application_enabled',
            field=models.BooleanField(default=False, help_text='Ellenőrök jelentkezhetnek meccsekre ebben a szakaszban', verbose_name='Ellenőr jelentkezés'),
        ),
        migrations.AddField(
            model_name='competitionphase',
            name='referee_application_enabled',
            field=models.BooleanField(default=False, help_text='Játékvezetők jelentkezhetnek meccsekre ebben a szakaszban', verbose_name='Játékvezető jelentkezés'),
        ),
        migrations.AddField(
            model_name='competitionphase',
            name='tournament_director_application_enabled',
            field=models.BooleanField(default=False, help_text='Tornaigazgatók jelentkezhetnek meccsekre ebben a szakaszban', verbose_name='Tornaigazgató jelentkezés'),
        ),
        migrations.AddField(
            model_name='competitionphase',
            name='tournament_director_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Tornaigazgatók száma'),
        ),
        migrations.CreateModel(
            name='MatchApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('referee', 'Játékvezető'), ('inspector', 'Ellenőr'), ('tournament_director', 'Tornaigazgató')], max_length=20, verbose_name='Szerepkör')),
                ('status', models.CharField(choices=[('pending', 'Várakozó'), ('accepted', 'Elfogadva'), ('withdrawn', 'Visszavonva')], default='pending', max_length=20, verbose_name='Státusz')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='matches.match', verbose_name='Mérkőzés')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_applications', to=settings.AUTH_USER_MODEL, verbose_name='Felhasználó')),
            ],
            options={
                'verbose_name': 'Mérkőzés jelentkezés',
                'verbose_name_plural': 'Mérkőzés jelentkezések',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'match', 'role')},
            },
        ),
    ]
