# Generated by Django 6.0.1 on 2026-01-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0019_competitionphase_inspector_application_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='inspector_application_default',
            field=models.BooleanField(default=False, help_text='Új szakaszok automatikusan öröklik', verbose_name='Ellenőr jelentkezés (alapértelmezett)'),
        ),
        migrations.AddField(
            model_name='competition',
            name='referee_application_default',
            field=models.BooleanField(default=False, help_text='Új szakaszok automatikusan öröklik', verbose_name='JV jelentkezés (alapértelmezett)'),
        ),
        migrations.AddField(
            model_name='competition',
            name='tournament_director_application_default',
            field=models.BooleanField(default=False, help_text='Új szakaszok automatikusan öröklik', verbose_name='TIG jelentkezés (alapértelmezett)'),
        ),
        migrations.AddField(
            model_name='competitionphase',
            name='inspector_payment',
            field=models.PositiveIntegerField(default=0, help_text='Díjazás ellenőrönként', verbose_name='Ellenőr díjazás (Ft)'),
        ),
        migrations.AddField(
            model_name='competitionphase',
            name='referee_payment',
            field=models.PositiveIntegerField(default=0, help_text='Díjazás játékvezetőnként', verbose_name='Játékvezető díjazás (Ft)'),
        ),
        migrations.AddField(
            model_name='competitionphase',
            name='tournament_director_payment',
            field=models.PositiveIntegerField(default=0, help_text='Díjazás tornaigazgatónként', verbose_name='Tornaigazgató díjazás (Ft)'),
        ),
    ]
