# Generated by Django 5.1.5 on 2026-01-29 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0020_add_position_payments_and_competition_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Klub neve')),
                ('short_name', models.CharField(blank=True, max_length=50, verbose_name='Rövid név')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Város')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='club_logos/', verbose_name='Logó')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
            ],
            options={
                'verbose_name': 'Klub',
                'verbose_name_plural': 'Klubbok',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-is_tbd', 'club__name', 'suffix'], 'verbose_name': 'Csapat', 'verbose_name_plural': 'Csapatok'},
        ),
        migrations.AddField(
            model_name='team',
            name='custom_name',
            field=models.CharField(blank=True, help_text='Ha meg van adva, ez jelenik meg a klub neve helyett', max_length=200, verbose_name='Egyedi teljes név'),
        ),
        migrations.AddField(
            model_name='team',
            name='suffix',
            field=models.CharField(blank=True, help_text='Pl. "U18", "Női" - a klub nevéhez adódik', max_length=100, verbose_name='Csapat megnevezés'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, help_text='Ha nincs megadva, a klub logója jelenik meg', null=True, upload_to='team_logos/', verbose_name='Saját logó'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Név'),
        ),
        migrations.AddField(
            model_name='team',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='matches.club', verbose_name='Klub'),
        ),
    ]
