# Generated by Django 5.1.5 on 2026-01-29 23:03

from django.db import migrations


def populate_clubs_from_teams(apps, schema_editor):
    """
    Create a Club for each existing Team and link them.
    Each Team becomes the main team of its own Club.
    """
    Team = apps.get_model('matches', 'Team')
    Club = apps.get_model('matches', 'Club')

    for team in Team.objects.all():
        # Create a club for each existing team
        club = Club.objects.create(
            name=team.name,
            short_name=team.short_name,
            city=team.city,
            logo=team.logo,
            is_active=team.is_active
        )
        # Link the team to its club
        team.club = club
        team.suffix = ''  # Main team, no suffix
        team.custom_name = ''  # Use club name
        team.save()


def reverse_populate(apps, schema_editor):
    """
    Reverse migration: copy club data back to teams and delete clubs.
    """
    Team = apps.get_model('matches', 'Team')
    Club = apps.get_model('matches', 'Club')

    for team in Team.objects.select_related('club').filter(club__isnull=False):
        # Copy club data back to team
        team.name = team.club.name
        team.short_name = team.club.short_name
        team.city = team.club.city
        team.logo = team.club.logo
        team.is_active = team.club.is_active
        team.club = None
        team.save()

    # Delete all clubs
    Club.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0021_add_club_model'),
    ]

    operations = [
        migrations.RunPython(populate_clubs_from_teams, reverse_populate),
    ]
