# Generated by Django 6.0.1 on 2026-01-29 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0022_populate_clubs_from_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Törlés időpontja'),
        ),
        migrations.AddField(
            model_name='club',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Törölve'),
        ),
        migrations.AddField(
            model_name='competition',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Törlés időpontja'),
        ),
        migrations.AddField(
            model_name='competition',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Törölve'),
        ),
        migrations.AddField(
            model_name='season',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Törlés időpontja'),
        ),
        migrations.AddField(
            model_name='season',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Törölve'),
        ),
        migrations.AddField(
            model_name='team',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Törlés időpontja'),
        ),
        migrations.AddField(
            model_name='team',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Törölve'),
        ),
        migrations.AddField(
            model_name='venue',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Törlés időpontja'),
        ),
        migrations.AddField(
            model_name='venue',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Törölve'),
        ),
    ]
