# Generated by Django 5.1.5 on 2026-01-29 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0023_add_soft_delete_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Bajnokság', 'verbose_name_plural': 'Bajnokságok'},
        ),
        migrations.AddField(
            model_name='competition',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Megjelenítési sorrend (kisebb szám = előrébb)', verbose_name='Sorrend'),
        ),
    ]
