# Generated by Django 5.1.5 on 2026-01-30 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0024_add_competition_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Cím'),
        ),
        migrations.AddField(
            model_name='club',
            name='country',
            field=models.CharField(blank=True, default='Magyarország', max_length=100, verbose_name='Ország'),
        ),
        migrations.AddField(
            model_name='club',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='club',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='club',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='club',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Irányítószám'),
        ),
        migrations.AddField(
            model_name='club',
            name='representative_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Képviselő email'),
        ),
        migrations.AddField(
            model_name='club',
            name='representative_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Képviselő neve'),
        ),
        migrations.AddField(
            model_name='club',
            name='representative_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Képviselő telefonszáma'),
        ),
        migrations.AddField(
            model_name='club',
            name='website',
            field=models.URLField(blank=True, verbose_name='Weboldal'),
        ),
        migrations.AddField(
            model_name='team',
            name='manager_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Csapatvezető email'),
        ),
        migrations.AddField(
            model_name='team',
            name='manager_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Csapatvezető neve'),
        ),
        migrations.AddField(
            model_name='team',
            name='manager_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Csapatvezető telefonszáma'),
        ),
        migrations.CreateModel(
            name='ClubContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Telefon'), ('website', 'Weboldal'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter/X'), ('other', 'Egyéb')], default='email', max_length=20, verbose_name='Típus')),
                ('label', models.CharField(blank=True, help_text='pl. "Titkárság", "Elnök"', max_length=100, verbose_name='Címke')),
                ('value', models.CharField(max_length=255, verbose_name='Érték')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='matches.club', verbose_name='Klub')),
            ],
            options={
                'verbose_name': 'Klub elérhetőség',
                'verbose_name_plural': 'Klub elérhetőségek',
                'ordering': ['contact_type', 'label'],
            },
        ),
    ]
