# Generated by Django 5.1.5 on 2026-01-30 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0025_add_club_team_extended_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='competitions',
            field=models.ManyToManyField(blank=True, help_text='A csapat melyik bajnokságokban vesz részt', related_name='teams', to='matches.competition', verbose_name='Bajnokságok'),
        ),
    ]
