# Generated by Django 5.1.5 on 2026-01-30 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0026_team_competitions'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionphase',
            name='inspector_payment_type',
            field=models.CharField(choices=[('per_person', 'Fő / mérkőzés'), ('total', 'Összesen / mérkőzés')], default='per_person', max_length=20, verbose_name='Ellenőr díjazás típusa'),
        ),
        migrations.AddField(
            model_name='competitionphase',
            name='referee_payment_type',
            field=models.CharField(choices=[('per_person', 'Fő / mérkőzés'), ('total', 'Összesen / mérkőzés')], default='per_person', max_length=20, verbose_name='JV díjazás típusa'),
        ),
        migrations.AddField(
            model_name='competitionphase',
            name='reserve_payment',
            field=models.PositiveIntegerField(default=0, help_text='Díjazás tartalékonként', verbose_name='Tartalék díjazás (Ft)'),
        ),
        migrations.AddField(
            model_name='competitionphase',
            name='reserve_payment_type',
            field=models.CharField(choices=[('per_person', 'Fő / mérkőzés'), ('total', 'Összesen / mérkőzés')], default='per_person', max_length=20, verbose_name='Tartalék díjazás típusa'),
        ),
        migrations.AddField(
            model_name='competitionphase',
            name='tournament_director_payment_type',
            field=models.CharField(choices=[('per_person', 'Fő / mérkőzés'), ('total', 'Összesen / mérkőzés')], default='per_person', max_length=20, verbose_name='TIG díjazás típusa'),
        ),
    ]
