# Generated by Django 5.1.5 on 2026-01-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0028_add_archive_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchassignment',
            name='application_enabled',
            field=models.BooleanField(
                default=False,
                help_text='Ha be van kapcsolva és a pozíció "Szükséges", akkor lehet rá jelentkezni',
                verbose_name='Jelentkezés engedélyezve'
            ),
        ),
    ]
