# Generated by Django 5.1.5 on 2026-01-30 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0029_add_assignment_application_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Ha be van jelölve, a mérkőzés az archívumba kerül', verbose_name='Archivált'),
        ),
        migrations.CreateModel(
            name='MatchFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('ok', 'Minden rendben'), ('red_card', 'Végleges kiállítás'), ('issue', 'Egyéb probléma')], max_length=20, verbose_name='Visszajelzés típusa')),
                ('notes', models.TextField(blank=True, verbose_name='Megjegyzés')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Beküldés időpontja')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítás időpontja')),
                ('reminder_1_sent', models.BooleanField(default=False)),
                ('reminder_3_sent', models.BooleanField(default=False)),
                ('reminder_5_sent', models.BooleanField(default=False)),
                ('reminder_7_sent', models.BooleanField(default=False)),
                ('reminder_10_sent', models.BooleanField(default=False)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='matches.matchassignment', verbose_name='Kiírás')),
            ],
            options={
                'verbose_name': 'Mérkőzés visszajelzés',
                'verbose_name_plural': 'Mérkőzés visszajelzések',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='RedCardReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_time', models.CharField(help_text='Formátum: MM:SS (pl. 15:30)', max_length=5, verbose_name='Jegyzőkönyvi idő')),
                ('violation_code', models.CharField(choices=[('10', '10) Játékos vagy csapatvezetés tagja elhagyja a csereterületet/büntetőpadot civakodásban való részvételhez'), ('11', '11) Játékos vagy csapatvezetés tagja verekedésben vesz részt'), ('12', '12) Játékos vagy csapatvezetés tagja brutális szabálytalanságot követ el, vagy kísérel meg elkövetni'), ('13', '13) Játékos vagy csapatvezetés tagja súlyos sportszerűtlen magatartást tanúsít'), ('14', '14) Játékos vagy csapatvezetés tagja fenyegető magatartást tanúsít')], max_length=10, verbose_name='Végleges kiállítás kódja (614/)')),
                ('offender_name', models.CharField(max_length=100, verbose_name='Elkövető neve')),
                ('offender_jersey_number', models.CharField(blank=True, max_length=10, verbose_name='Mezszám')),
                ('offender_function', models.CharField(choices=[('player', 'Játékos'), ('official', 'Hivatalos személy (Edző, csapatvezető, ...)'), ('other', 'Egyéb')], max_length=20, verbose_name='Elkövető funkciója')),
                ('offender_function_other', models.CharField(blank=True, max_length=100, verbose_name='Egyéb funkció')),
                ('incident_description', models.TextField(verbose_name='Incidens leírása')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozás időpontja')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_cards', to='matches.matchfeedback', verbose_name='Visszajelzés')),
            ],
            options={
                'verbose_name': 'Piros lap jelentés',
                'verbose_name_plural': 'Piros lap jelentések',
                'ordering': ['incident_time'],
            },
        ),
        migrations.CreateModel(
            name='RedCardWitness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Név')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefonszám')),
                ('red_card_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witnesses', to='matches.redcardreport', verbose_name='Piros lap jelentés')),
            ],
            options={
                'verbose_name': 'Tanú',
                'verbose_name_plural': 'Tanúk',
            },
        ),
    ]
