# Generated by Django 6.0.1 on 2026-01-20 18:17

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        ('referees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('referee', 'Játékvezető'), ('inspector', 'Ellenőr'), ('reserve', 'Tartalék')], max_length=20, verbose_name='Szerep')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Összeg (Ft)')),
                ('valid_from', models.DateField(verbose_name='Érvényes ettől')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Érvényes eddig')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='matches.competitionphase', verbose_name='Szakasz')),
            ],
            options={
                'verbose_name': 'Díjazási struktúra',
                'verbose_name_plural': 'Díjazási struktúrák',
                'ordering': ['phase', 'role', '-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='MatchFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Alap összeg')),
                ('split_ratio', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=3, verbose_name='Megosztási arány')),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Végső összeg')),
                ('manual_adjustment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Manuális korrekció')),
                ('adjustment_reason', models.CharField(blank=True, max_length=300, verbose_name='Korrekció indoka')),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee', to='matches.matchassignment', verbose_name='Kijelölés')),
            ],
            options={
                'verbose_name': 'Mérkőzés díj',
                'verbose_name_plural': 'Mérkőzés díjak',
            },
        ),
        migrations.CreateModel(
            name='MonthlyStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Év')),
                ('month', models.PositiveIntegerField(verbose_name='Hónap')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Teljes összeg')),
                ('match_count', models.PositiveIntegerField(default=0, verbose_name='Mérkőzések száma')),
                ('status', models.CharField(choices=[('draft', 'Piszkozat'), ('pending', 'Jóváhagyásra vár'), ('approved', 'Jóváhagyva'), ('paid', 'Kifizetve')], default='draft', max_length=20, verbose_name='Státusz')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Jóváhagyás dátuma')),
                ('notes', models.TextField(blank=True, verbose_name='Megjegyzés')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_statements', to=settings.AUTH_USER_MODEL, verbose_name='Jóváhagyta')),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_statements', to='referees.referee', verbose_name='Játékvezető')),
            ],
            options={
                'verbose_name': 'Havi elszámolás',
                'verbose_name_plural': 'Havi elszámolások',
                'ordering': ['-year', '-month'],
                'unique_together': {('referee', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='StatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement_lines', to='billing.matchfee', verbose_name='Mérkőzés díj')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.monthlystatement', verbose_name='Elszámolás')),
            ],
            options={
                'verbose_name': 'Elszámolás sor',
                'verbose_name_plural': 'Elszámolás sorok',
                'unique_together': {('statement', 'match_fee')},
            },
        ),
    ]
