# Generated by Django 5.1.5 on 2026-01-25 07:27

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('matches', '0013_add_soft_delete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructure',
            name='role',
            field=models.CharField(choices=[('referee', 'Játékvezető'), ('reserve', 'Tartalék'), ('inspector', 'Ellenőr'), ('tournament_director', 'Tornaigazgató')], max_length=20, verbose_name='Szerep'),
        ),
        migrations.CreateModel(
            name='TravelCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('none', 'Nincs'), ('car', 'Autós kiküldetés'), ('public', 'Tömegközlekedés')], default='none', max_length=20, verbose_name='Költség típus')),
                ('distance_km', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Távolság (km)')),
                ('car_rate_per_km', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, verbose_name='Km díj (Ft/km)')),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='travel_receipts/', verbose_name='Számla')),
                ('receipt_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Számla összeg')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Összeg (Ft)')),
                ('status', models.CharField(choices=[('pending', 'Jóváhagyásra vár'), ('approved', 'Jóváhagyva'), ('rejected', 'Elutasítva')], default='pending', max_length=20, verbose_name='Státusz')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Elbírálás dátuma')),
                ('comment', models.TextField(blank=True, verbose_name='Megjegyzés')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='travel_cost', to='matches.matchassignment', verbose_name='Kijelölés')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_travel_costs', to=settings.AUTH_USER_MODEL, verbose_name='Elbíráló')),
            ],
            options={
                'verbose_name': 'Utazási költség',
                'verbose_name_plural': 'Utazási költségek',
                'ordering': ['-created_at'],
            },
        ),
    ]
