# Generated by Django 5.1.5 on 2026-01-25 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_travel_cost'),
        ('matches', '0013_add_soft_delete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declaration_type', models.CharField(choices=[('efo', 'EFO'), ('ekho', 'EKHO')], max_length=10, verbose_name='Bejelentés típus')),
                ('status', models.CharField(choices=[('pending', 'Bejelentésre vár'), ('declared', 'Bejelentett'), ('modified', 'Módosítás történt')], default='pending', max_length=20, verbose_name='Státusz')),
                ('declared_date', models.DateField(blank=True, null=True, verbose_name='Bejelentett dátum')),
                ('declared_time', models.TimeField(blank=True, null=True, verbose_name='Bejelentett időpont')),
                ('declared_venue_id', models.IntegerField(blank=True, null=True, verbose_name='Bejelentett helyszín ID')),
                ('declared_referees', models.JSONField(blank=True, default=list, verbose_name='Bejelentett játékvezetők')),
                ('changes_detected', models.JSONField(blank=True, default=list, verbose_name='Észlelt változások')),
                ('declared_at', models.DateTimeField(blank=True, null=True, verbose_name='Bejelentés időpontja')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_declaration', to='matches.matchassignment', verbose_name='Kijelölés')),
                ('declared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_declarations', to=settings.AUTH_USER_MODEL, verbose_name='Bejelentette')),
            ],
            options={
                'verbose_name': 'Adóbejelentés',
                'verbose_name_plural': 'Adóbejelentések',
                'ordering': ['-created_at'],
            },
        ),
    ]
