# Generated by Django 5.1.5 on 2026-01-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_tax_declaration'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelcost',
            name='scan_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='VirusTotal scan ID'),
        ),
        migrations.AddField(
            model_name='travelcost',
            name='scan_result',
            field=models.JSONField(blank=True, default=dict, verbose_name='Ellenőrzés eredménye'),
        ),
        migrations.AddField(
            model_name='travelcost',
            name='scan_status',
            field=models.CharField(choices=[('not_scanned', 'Nem ellenőrzött'), ('scanning', 'Ellenőrzés alatt'), ('clean', 'Tiszta'), ('infected', 'Fertőzött'), ('error', 'Hiba')], default='not_scanned', max_length=20, verbose_name='Vírusellenőrzés státusz'),
        ),
        migrations.AddField(
            model_name='travelcost',
            name='scanned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ellenőrzés időpontja'),
        ),
    ]
