# Generated by Django 5.1.5 on 2026-01-27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_add_virustotal_scan_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelcost',
            name='scan_id',
        ),
        migrations.RemoveField(
            model_name='travelcost',
            name='scan_result',
        ),
        migrations.RemoveField(
            model_name='travelcost',
            name='scan_status',
        ),
        migrations.RemoveField(
            model_name='travelcost',
            name='scanned_at',
        ),
    ]
