# Generated by Django 5.1.5 on 2026-01-28 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_remove_virustotal_scan_fields'),
        ('matches', '0013_add_soft_delete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taxdeclaration',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_declarations', to='matches.match', verbose_name='Mérkőzés'),
        ),
        migrations.AddField(
            model_name='taxdeclaration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tax_declarations', to=settings.AUTH_USER_MODEL, verbose_name='Játékvezető'),
        ),
        migrations.AlterField(
            model_name='taxdeclaration',
            name='assignment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_declaration', to='matches.matchassignment', verbose_name='Kijelölés'),
        ),
        migrations.AlterField(
            model_name='travelcost',
            name='status',
            field=models.CharField(choices=[('pending', 'Jóváhagyásra vár'), ('approved', 'Jóváhagyva'), ('rejected', 'Elutasítva'), ('returned', 'Visszaküldve'), ('declined', 'Nem igényelt')], default='pending', max_length=20, verbose_name='Státusz'),
        ),
    ]
