# Generated by Django 5.1.5 on 2026-01-28 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_add_match_user_to_tax_declaration'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxdeclaration',
            name='hidden_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Elrejtés időpontja'),
        ),
        migrations.AddField(
            model_name='taxdeclaration',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Elrejtve'),
        ),
    ]
