# Generated by Django 6.0.1 on 2026-01-20 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefonszám')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Irányítószám')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Város')),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='Közterület')),
                ('street_type', models.CharField(blank=True, max_length=50, verbose_name='Közterület típusa')),
                ('house_number', models.CharField(blank=True, max_length=20, verbose_name='Házszám')),
                ('floor_door', models.CharField(blank=True, max_length=50, verbose_name='Emelet/ajtó')),
                ('has_travel_reimbursement', models.BooleanField(default=False, verbose_name='Van útiköltség-térítés')),
                ('drivers_license_number', models.CharField(blank=True, max_length=50, verbose_name='Vezetői engedély szám')),
                ('car_brand', models.CharField(blank=True, max_length=50, verbose_name='Autó márkája')),
                ('car_model', models.CharField(blank=True, max_length=50, verbose_name='Autó típusa')),
                ('car_plate', models.CharField(blank=True, max_length=20, verbose_name='Rendszám')),
                ('medical_valid_until', models.DateField(blank=True, null=True, verbose_name='Sportorvosi érvényessége')),
                ('license_level', models.CharField(choices=[('C', 'C'), ('C+', 'C+'), ('B', 'B'), ('B+', 'B+'), ('A', 'A'), ('A+', 'A+')], default='C', max_length=5, verbose_name='Licenc szint')),
                ('international_level', models.CharField(blank=True, choices=[('', 'Nincs'), ('C', 'C'), ('B', 'B'), ('A', 'A')], default='', max_length=5, verbose_name='Nemzetközi szint')),
                ('billing_type', models.CharField(choices=[('full_ekho', 'Teljes EKHO'), ('partial_ekho', 'Részben EKHO'), ('student', 'Diák'), ('efo', 'EFO')], default='efo', max_length=20, verbose_name='Elszámolás típus')),
                ('status', models.CharField(choices=[('active', 'Aktív'), ('inactive', 'Inaktív')], default='active', max_length=10, verbose_name='Státusz')),
                ('jb_notes', models.TextField(blank=True, verbose_name='JB megjegyzések')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referee_profile', to=settings.AUTH_USER_MODEL, verbose_name='Felhasználó')),
            ],
            options={
                'verbose_name': 'Játékvezető',
                'verbose_name_plural': 'Játékvezetők',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Unavailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Kezdete')),
                ('end_date', models.DateField(verbose_name='Vége')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Indok')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailabilities', to='referees.referee', verbose_name='Játékvezető')),
            ],
            options={
                'verbose_name': 'Szabadság',
                'verbose_name_plural': 'Szabadságok',
                'ordering': ['-start_date'],
            },
        ),
    ]
