# Generated by Django 5.1.5 on 2026-01-27 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0013_add_soft_delete'),
        ('referees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Piszkozat'), ('submitted', 'Beküldve')], default='draft', max_length=20, verbose_name='Státusz')),
                ('general_notes', models.TextField(blank=True, verbose_name='Általános megjegyzések')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspector_reports', to=settings.AUTH_USER_MODEL, verbose_name='Ellenőr')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspector_reports', to='matches.match', verbose_name='Mérkőzés')),
            ],
            options={
                'verbose_name': 'Ellenőri jelentés',
                'verbose_name_plural': 'Ellenőri jelentések',
                'ordering': ['-created_at'],
                'unique_together': {('match', 'inspector')},
            },
        ),
        migrations.CreateModel(
            name='RefereeEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules_knowledge', models.PositiveSmallIntegerField(default=3, help_text='1-5 értékelés', verbose_name='Szabályismeret')),
                ('positioning', models.PositiveSmallIntegerField(default=3, help_text='1-5 értékelés', verbose_name='Mozgás, elhelyezkedés')),
                ('communication', models.PositiveSmallIntegerField(default=3, help_text='1-5 értékelés', verbose_name='Kommunikáció')),
                ('fitness', models.PositiveSmallIntegerField(default=3, help_text='1-5 értékelés', verbose_name='Fizikai felkészültség')),
                ('overall_rating', models.PositiveSmallIntegerField(default=3, help_text='1-5 értékelés', verbose_name='Összértékelés')),
                ('notes', models.TextField(blank=True, verbose_name='Megjegyzések')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='Játékvezető')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='referees.inspectorreport', verbose_name='Jelentés')),
            ],
            options={
                'verbose_name': 'Játékvezető értékelés',
                'verbose_name_plural': 'Játékvezető értékelések',
                'ordering': ['report', 'referee__last_name'],
                'unique_together': {('report', 'referee')},
            },
        ),
    ]
