# Generated by Django 6.0.1 on 2026-01-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_admin_module',
        ),
        migrations.RemoveField(
            model_name='user',
            name='has_billing_module',
        ),
        migrations.RemoveField(
            model_name='user',
            name='has_content_module',
        ),
        migrations.RemoveField(
            model_name='user',
            name='has_inspector_module',
        ),
        migrations.RemoveField(
            model_name='user',
            name='has_matches_module',
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefonszám'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Profilkép'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('referee', 'Játékvezető'), ('jt_admin', 'JT Admin / Koordinátor'), ('vb', 'VB tag'), ('inspector', 'Ellenőr'), ('accountant', 'Könyvelő'), ('admin', 'Adminisztrátor')], default='referee', max_length=20, verbose_name='Szerepkör'),
        ),
    ]
