# Generated by Django 5.1.5 on 2026-01-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_has_admin_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Cím'),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_account',
            field=models.CharField(blank=True, max_length=30, verbose_name='Bankszámlaszám'),
        ),
        migrations.AddField(
            model_name='user',
            name='billing_type',
            field=models.CharField(choices=[('nincs', 'Nincs'), ('efo', 'EFO'), ('ekho', 'EKHO')], default='nincs', max_length=10, verbose_name='Elszámolás típusa'),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Születési idő'),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_place',
            field=models.CharField(blank=True, max_length=100, verbose_name='Születési hely'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Város'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, default='Magyarország', max_length=100, verbose_name='Ország'),
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Törlés időpontja'),
        ),
        migrations.AddField(
            model_name='user',
            name='has_content_module',
            field=models.BooleanField(default=False, verbose_name='Tartalomgyártó modul'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Törölve'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_hidden_from_colleagues',
            field=models.BooleanField(default=False, verbose_name='Rejtett a kollégák között'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_inspector_flag',
            field=models.BooleanField(default=False, verbose_name='Ellenőr modul'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_login_disabled',
            field=models.BooleanField(default=False, verbose_name='Bejelentkezés letiltva'),
        ),
        migrations.AddField(
            model_name='user',
            name='mother_maiden_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Anyja leánykori neve'),
        ),
        migrations.AddField(
            model_name='user',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Irányítószám'),
        ),
        migrations.AddField(
            model_name='user',
            name='taj_number',
            field=models.CharField(blank=True, max_length=12, verbose_name='TAJ szám'),
        ),
        migrations.AddField(
            model_name='user',
            name='tax_id',
            field=models.CharField(blank=True, max_length=15, verbose_name='Adóazonosító jel'),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_authorization',
            field=models.BooleanField(default=False, verbose_name='Van meghatalmazás'),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_engine_cc',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Motor (cm³)'),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_engine_type',
            field=models.CharField(blank=True, choices=[('benzin', 'Benzin'), ('diesel', 'Dízel'), ('elektromos', 'Elektromos'), ('hibrid', 'Hibrid'), ('lpg', 'LPG')], max_length=20, verbose_name='Motor típusa'),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_license_plate',
            field=models.CharField(blank=True, max_length=20, verbose_name='Rendszám'),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_make',
            field=models.CharField(blank=True, max_length=50, verbose_name='Gépjármű gyártó'),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=50, verbose_name='Gépjármű modell'),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_owner',
            field=models.CharField(blank=True, max_length=100, verbose_name='Gépjármű tulajdonos neve'),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Gyártás éve'),
        ),
    ]
