# Generated by Django 5.1.5 on 2026-01-25 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_extended_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_accountant_flag',
            field=models.BooleanField(default=False, verbose_name='Könyvelő jogosultság'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin_flag',
            field=models.BooleanField(default=False, verbose_name='Admin jogosultság'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_jt_admin_flag',
            field=models.BooleanField(default=False, verbose_name='JT Admin jogosultság'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_vb_flag',
            field=models.BooleanField(default=False, verbose_name='VB tag jogosultság'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_inspector_flag',
            field=models.BooleanField(default=False, verbose_name='Ellenőr jogosultság'),
        ),
    ]
