# Generated by Django 5.1.5 on 2026-01-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_role_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_referee_flag',
            field=models.BooleanField(default=False, verbose_name='Játékvezető (megjelenik a kollégák között)'),
        ),
    ]
