# Generated by Django 5.1.5 on 2026-01-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_referee_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_cancellation_hours', models.PositiveIntegerField(default=96, help_text='Ha a mérkőzés ennyi órán belül van, a játékvezető nem mondhatja le önállóan.', verbose_name='Minimum lemondási idő (óra)')),
                ('coordinator_name', models.CharField(default='Koordinátor', max_length=100, verbose_name='Koordinátor neve')),
                ('coordinator_phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Koordinátor telefonszáma')),
            ],
            options={
                'verbose_name': 'Rendszer beállítások',
                'verbose_name_plural': 'Rendszer beállítások',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('referee', 'Játékvezető'), ('jt_admin', 'JT Admin'), ('vb', 'VB tag'), ('inspector', 'Ellenőr'), ('accountant', 'Könyvelő'), ('admin', 'Adminisztrátor')], default='referee', max_length=20, verbose_name='Szerepkör'),
        ),
    ]
