# Generated by Django 5.1.5 on 2026-01-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_site_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Név')),
                ('phone', models.CharField(max_length=30, verbose_name='Telefonszám')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sorrend')),
            ],
            options={
                'verbose_name': 'Koordinátor',
                'verbose_name_plural': 'Koordinátorok',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='coordinator_name',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='coordinator_phone',
        ),
    ]
