# Generated by Django 5.1.5 on 2026-01-27 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_coordinator_user_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Aktív'),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coordinator_entry', to=settings.AUTH_USER_MODEL, verbose_name='Felhasználó'),
        ),
    ]
