# Generated by Django 5.1.5 on 2026-01-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_coordinator_optimizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vehicle_reimbursement_enabled',
            field=models.BooleanField(default=False, help_text='Ha be van kapcsolva, a felhasználó feltölthet autós útiköltséget', verbose_name='Gépjármű elszámolás engedélyezve'),
        ),
    ]
