# Generated by Django 5.1.5 on 2026-01-28 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_vehicle_reimbursement_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='medical_valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Sportorvosi érvényessége'),
        ),
    ]
