# Generated by Django 5.1.5 on 2026-01-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_add_medical_valid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='failed_login_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Sikertelen bejelentkezések'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_failed_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Utolsó sikertelen bejelentkezés'),
        ),
    ]
