# Generated by Django 5.1.5 on 2026-01-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_failed_login_count_user_last_failed_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=True, help_text='Első belépéskor kötelező jelszót változtatni', verbose_name='Jelszó változtatás szükséges'),
        ),
    ]
