# Generated by Django 5.1.5 on 2026-01-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_add_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_super_admin',
            field=models.BooleanField(default=False, help_text='Védett admin: nem kitiltható, végleges törlés, teljes napló. Csak Django adminból állítható!', verbose_name='Szuper Admin'),
        ),
    ]
