# Generated by Django 6.0.1 on 2026-01-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_add_super_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='require_cancellation_reason',
            field=models.BooleanField(default=True, help_text='Ha be van kapcsolva, a játékvezetőnek indokot kell megadnia lemondáskor.', verbose_name='Lemondási indok kötelező'),
        ),
    ]
