# Generated by Django 6.0.1 on 2026-01-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_sitesettings_require_cancellation_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_match_assignment', models.BooleanField(default=True, help_text='Értesítés új mérkőzés kiíráskor', verbose_name='Új kiírás értesítés')),
                ('notify_match_reminder', models.BooleanField(default=True, help_text='Emlékeztető értesítés a mérkőzés előtt', verbose_name='Mérkőzés emlékeztető')),
                ('notify_match_cancellation', models.BooleanField(default=True, help_text='Értesítés mérkőzés lemondáskor (adminoknak)', verbose_name='Lemondás értesítés')),
                ('notify_match_modification', models.BooleanField(default=True, help_text='Értesítés mérkőzés adatainak módosításakor', verbose_name='Mérkőzés módosítás értesítés')),
                ('notify_efo', models.BooleanField(default=True, help_text='EFO bejelentés értesítések', verbose_name='EFO értesítés')),
                ('notify_travel_expense', models.BooleanField(default=True, help_text='Útiköltség jóváhagyás/visszaküldés értesítések', verbose_name='Útiköltség értesítés')),
                ('notify_news', models.BooleanField(default=True, help_text='Új hír megjelenésekor értesítés', verbose_name='Hírek értesítés')),
                ('notify_mandatory_news', models.BooleanField(default=True, help_text='Kötelező elolvasandó hírek értesítése', verbose_name='Kötelező hírek értesítés')),
                ('notify_report', models.BooleanField(default=True, help_text='Ellenőri jelentés beérkezésekor értesítés', verbose_name='Jelentés értesítés')),
                ('notify_medical_expiry', models.BooleanField(default=True, help_text='Orvosi alkalmassági lejárat előtti emlékeztető', verbose_name='Orvosi lejárat értesítés')),
                ('notify_failed_logins', models.BooleanField(default=True, help_text='Értesítés többszöri sikertelen bejelentkezéskor (adminoknak)', verbose_name='Sikertelen bejelentkezés értesítés')),
            ],
            options={
                'verbose_name': 'Értesítés beállítások',
                'verbose_name_plural': 'Értesítés beállítások',
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='max_failed_login_attempts',
            field=models.PositiveIntegerField(default=10, help_text='Ennyi sikertelen bejelentkezés után értesítést kapnak az adminok.', verbose_name='Max. hibás bejelentkezés'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='session_timeout_hours',
            field=models.PositiveIntegerField(default=8, help_text='Ennyi óra inaktivitás után automatikusan kijelentkezteti a felhasználót.', verbose_name='Session időtartam (óra)'),
        ),
    ]
