# Generated by Django 6.0.1 on 2026-01-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_notificationsettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='application_inspectors_enabled',
            field=models.BooleanField(default=False, help_text='Ellenőrök jelentkezhetnek meccsekre', verbose_name='Ellenőr jelentkezés'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='application_referees_enabled',
            field=models.BooleanField(default=False, help_text='Játékvezetők jelentkezhetnek meccsekre', verbose_name='Játékvezető jelentkezés'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='application_tournament_directors_enabled',
            field=models.BooleanField(default=False, help_text='Tornaigazgatók jelentkezhetnek meccsekre', verbose_name='Tornaigazgató jelentkezés'),
        ),
    ]
