# Generated by Django 6.0.1 on 2026-01-29 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_sitesettings_application_inspectors_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='match_reminder_days',
            field=models.PositiveIntegerField(default=2, help_text='Hány nappal a mérkőzés előtt küldjön emlékeztetőt', verbose_name='Emlékeztető nappal előtte'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='medical_expiry_reminder_days',
            field=models.PositiveIntegerField(default=30, help_text='Hány nappal a lejárat előtt küldjön emlékeztetőt', verbose_name='Orvosi lejárat emlékeztető (nap)'),
        ),
    ]
