# Generated by Django 6.0.1 on 2026-01-29 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_add_notification_timing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_tournament_director_flag',
            field=models.BooleanField(default=False, verbose_name='Tornaigazgató jogosultság'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('referee', 'Játékvezető'), ('tournament_director', 'Tornaigazgató'), ('jt_admin', 'JT Admin'), ('vb', 'VB tag'), ('inspector', 'Ellenőr'), ('accountant', 'Könyvelő'), ('admin', 'Adminisztrátor')], default='referee', max_length=20, verbose_name='Szerepkör'),
        ),
    ]
