# Generated by Django 5.1.5 on 2026-01-30 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_add_user_archive_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facebook_link',
            field=models.URLField(blank=True, help_text='Facebook profil vagy Messenger link a gyors kapcsolatfelvételhez', max_length=255, verbose_name='Facebook/Messenger link'),
        ),
        migrations.AlterField(
            model_name='user',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Kizárás időpontja'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Ha be van jelölve, a felhasználó nem tud bejelentkezni', verbose_name='Kizárt'),
        ),
    ]
