# Generated by Django 5.1.5 on 2026-01-30 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_add_facebook_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='admin_notification_emails',
            field=models.TextField(blank=True, help_text='Vesszővel elválasztott e-mail címek, akik kritikus értesítéseket kapnak.', verbose_name='Admin értesítési e-mail címek'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_enabled',
            field=models.BooleanField(default=True, help_text='Ha kikapcsolod, a rendszer nem küld e-maileket senkinek.', verbose_name='E-mail küldés engedélyezve'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='notify_security_alerts',
            field=models.BooleanField(default=True, help_text='Bot támadások, szokatlan bejelentkezések értesítése', verbose_name='Biztonsági figyelmeztetések'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='notify_server_issues',
            field=models.BooleanField(default=True, help_text='Kritikus szerver állapot értesítések (RAM, CPU, tárhely)', verbose_name='Szerver problémák értesítés'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='notify_unusual_login_countries',
            field=models.BooleanField(default=True, help_text='Értesítés ha valaki szokatlan helyről jelentkezik be', verbose_name='Szokatlan országból bejelentkezés'),
        ),
    ]
