# Generated by Django 5.1.5 on 2026-01-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_add_email_and_security_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='notify_match_reminder_pending',
            field=models.BooleanField(default=True, help_text='Emlékeztető email a még nem elfogadott mérkőzésekről', verbose_name='Mérkőzés emlékeztető (nem elfogadott)'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='match_reminder_hours',
            field=models.PositiveIntegerField(default=24, help_text='Hány órával a mérkőzés előtt küldjön emlékeztetőt (alapértelmezett: 24 óra = 1 nap)', verbose_name='Emlékeztető órával előtte'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='notify_match_reminder',
            field=models.BooleanField(default=True, help_text='Emlékeztető email az elfogadott mérkőzésekről', verbose_name='Mérkőzés emlékeztető (elfogadott)'),
        ),
    ]
