# Generated by Django 6.0.1 on 2026-01-20 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Cím')),
                ('description', models.TextField(blank=True, verbose_name='Leírás')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sorrend')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kurzus',
                'verbose_name_plural': 'Kurzusok',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Cím')),
                ('description', models.TextField(blank=True, verbose_name='Leírás')),
                ('passing_score', models.PositiveIntegerField(default=60, verbose_name='Minimum pontszám (%)')),
                ('time_limit_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Időkorlát (perc)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='education.course', verbose_name='Kurzus')),
            ],
            options={
                'verbose_name': 'Vizsga',
                'verbose_name_plural': 'Vizsgák',
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Pontszám')),
                ('max_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Max pontszám')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Százalék')),
                ('status', models.CharField(choices=[('in_progress', 'Folyamatban'), ('completed', 'Befejezett'), ('passed', 'Sikeres'), ('failed', 'Sikertelen')], default='in_progress', max_length=20, verbose_name='Státusz')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='education.exam', verbose_name='Vizsga')),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to='referees.referee', verbose_name='Játékvezető')),
            ],
            options={
                'verbose_name': 'Vizsgakísérlet',
                'verbose_name_plural': 'Vizsgakísérletek',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Cím')),
                ('content', models.TextField(verbose_name='Tartalom')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sorrend')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='education.course', verbose_name='Kurzus')),
            ],
            options={
                'verbose_name': 'Lecke',
                'verbose_name_plural': 'Leckék',
                'ordering': ['course', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LessonAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Cím')),
                ('file', models.FileField(upload_to='education/attachments/', verbose_name='Fájl')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='education.lesson', verbose_name='Lecke')),
            ],
            options={
                'verbose_name': 'Csatolmány',
                'verbose_name_plural': 'Csatolmányok',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Kérdés')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sorrend')),
                ('points', models.PositiveIntegerField(default=1, verbose_name='Pontszám')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='education.exam', verbose_name='Vizsga')),
            ],
            options={
                'verbose_name': 'Kérdés',
                'verbose_name_plural': 'Kérdések',
                'ordering': ['exam', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Válasz')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Helyes')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sorrend')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='education.question', verbose_name='Kérdés')),
            ],
            options={
                'verbose_name': 'Válasz',
                'verbose_name_plural': 'Válaszok',
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Helyes')),
                ('selected_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.answer', verbose_name='Választott válasz')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_answers', to='education.examattempt', verbose_name='Kísérlet')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.question', verbose_name='Kérdés')),
            ],
            options={
                'verbose_name': 'Adott válasz',
                'verbose_name_plural': 'Adott válaszok',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
