# Generated by Django 5.1.5 on 2026-01-25 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Cím')),
                ('content', models.TextField(blank=True, verbose_name='Tartalom')),
                ('post_type', models.CharField(choices=[('article', 'Cikk'), ('video', 'Videó'), ('document', 'Dokumentum')], default='article', max_length=20, verbose_name='Típus')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='knowledge/thumbnails/', verbose_name='Borítókép')),
                ('video_url', models.URLField(blank=True, help_text='YouTube vagy más videó link', verbose_name='Videó URL')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='knowledge/attachments/', verbose_name='Csatolmány')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_posts', to=settings.AUTH_USER_MODEL, verbose_name='Létrehozta')),
            ],
            options={
                'verbose_name': 'Tudástár bejegyzés',
                'verbose_name_plural': 'Tudástár bejegyzések',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Cím')),
                ('content', models.TextField(verbose_name='Tartalom')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Kép')),
                ('is_published', models.BooleanField(default=False, verbose_name='Közzétéve')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Kitűzött')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Közzététel ideje')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_posts', to=settings.AUTH_USER_MODEL, verbose_name='Létrehozta')),
            ],
            options={
                'verbose_name': 'Hír',
                'verbose_name_plural': 'Hírek',
                'ordering': ['-is_pinned', '-published_at', '-created_at'],
            },
        ),
    ]
