# Generated by Django 5.1.5 on 2026-01-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_add_knowledge_post_and_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text='Ha be van állítva, a hír automatikusan közzé lesz téve ezen időpontban', null=True, verbose_name='Időzített közzététel'),
        ),
    ]
