# Generated by Django 5.1.5 on 2026-01-27 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_add_news_scheduled_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgepost',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Tudástár bejegyzés', 'verbose_name_plural': 'Tudástár bejegyzések'},
        ),
        migrations.RemoveField(
            model_name='knowledgepost',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='knowledgepost',
            name='post_type',
        ),
        migrations.AddField(
            model_name='knowledgepost',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='Piszkozatként mentett bejegyzéseket csak adminok látják', verbose_name='Piszkozat'),
        ),
        migrations.AddField(
            model_name='knowledgepost',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Sorrend'),
        ),
        migrations.AlterField(
            model_name='knowledgepost',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube videó link (pl. https://youtube.com/watch?v=...)', verbose_name='YouTube videó URL'),
        ),
        migrations.CreateModel(
            name='KnowledgeAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='knowledge/attachments/', verbose_name='Fájl')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Eredeti fájlnév')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='education.knowledgepost', verbose_name='Bejegyzés')),
            ],
            options={
                'verbose_name': 'Csatolmány',
                'verbose_name_plural': 'Csatolmányok',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
