# Generated by Django 5.1.5 on 2026-01-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_refactor_knowledge_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgepost',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text='Ha beállítod, a bejegyzés automatikusan megjelenik a megadott időpontban', null=True, verbose_name='Időzített közzététel'),
        ),
    ]
