# Generated by Django 5.1.5 on 2026-01-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_add_scheduled_at_to_knowledgepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgepost',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Elrejtett bejegyzéseket csak adminok látják', verbose_name='Elrejtett'),
        ),
    ]
