# Generated by Django 5.1.5 on 2026-01-27 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_add_is_hidden_order_to_news'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Név')),
                ('description', models.TextField(blank=True, verbose_name='Leírás')),
                ('icon', models.CharField(default='folder', help_text='Material Icons név (pl. folder, school, sports)', max_length=50, verbose_name='Ikon')),
                ('color', models.CharField(default='#3b82f6', help_text='Hex színkód (pl. #3b82f6)', max_length=20, verbose_name='Szín')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sorrend')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_categories', to=settings.AUTH_USER_MODEL, verbose_name='Létrehozta')),
            ],
            options={
                'verbose_name': 'Dokumentum kategória',
                'verbose_name_plural': 'Dokumentum kategóriák',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Cím')),
                ('description', models.TextField(blank=True, verbose_name='Leírás')),
                ('document_type', models.CharField(choices=[('file', 'Fájl'), ('link', 'Link'), ('youtube', 'YouTube')], default='file', max_length=20, verbose_name='Típus')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Fájl')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='Eredeti fájlnév')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sorrend')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Létrehozta')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='education.documentcategory', verbose_name='Kategória')),
            ],
            options={
                'verbose_name': 'Dokumentum',
                'verbose_name_plural': 'Dokumentumok',
                'ordering': ['category', 'order', 'title'],
            },
        ),
    ]
