# Generated by Django 5.1.5 on 2026-01-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_add_document_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_system_news',
            field=models.BooleanField(default=False, help_text='Rendszerhír esetén a szerző "JAR Rendszer"-ként jelenik meg', verbose_name='Rendszerhír'),
        ),
    ]
