# Generated by Django 6.0.1 on 2026-01-20 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Név')),
                ('description', models.TextField(blank=True, verbose_name='Leírás')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sorrend')),
            ],
            options={
                'verbose_name': 'Dokumentum kategória',
                'verbose_name_plural': 'Dokumentum kategóriák',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Cím')),
                ('description', models.TextField(blank=True, verbose_name='Leírás')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('is_public', models.BooleanField(default=False, help_text='Mindenki láthatja, nem csak bejelentkezett felhasználók', verbose_name='Publikus')),
                ('requires_jb_access', models.BooleanField(default=False, help_text='Csak JB tagok láthatják', verbose_name='JB hozzáférés szükséges')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documentcategory', verbose_name='Kategória')),
            ],
            options={
                'verbose_name': 'Dokumentum',
                'verbose_name_plural': 'Dokumentumok',
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Cím')),
                ('message', models.TextField(verbose_name='Üzenet')),
                ('notification_type', models.CharField(choices=[('info', 'Információ'), ('warning', 'Figyelmeztetés'), ('success', 'Sikeres'), ('error', 'Hiba'), ('match', 'Mérkőzés')], default='info', max_length=20, verbose_name='Típus')),
                ('is_read', models.BooleanField(default=False, verbose_name='Olvasott')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Olvasva')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='Link')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Címzett')),
            ],
            options={
                'verbose_name': 'Értesítés',
                'verbose_name_plural': 'Értesítések',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=20, verbose_name='Verziószám')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Fájl')),
                ('changelog', models.TextField(blank=True, verbose_name='Változások')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document', verbose_name='Dokumentum')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Feltöltötte')),
            ],
            options={
                'verbose_name': 'Dokumentum verzió',
                'verbose_name_plural': 'Dokumentum verziók',
                'ordering': ['-uploaded_at'],
                'unique_together': {('document', 'version_number')},
            },
        ),
    ]
