# Generated by Django 5.1.5 on 2026-01-28 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Időpont')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP cím')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='Böngésző')),
                ('category', models.CharField(choices=[('auth', 'Hitelesítés'), ('match', 'Mérkőzés'), ('assignment', 'Kiírás'), ('declaration', 'Bejelentés'), ('document', 'Dokumentum'), ('user', 'Felhasználó'), ('travel', 'Útiköltség'), ('report', 'Jelentés'), ('system', 'Rendszer'), ('email', 'Email')], db_index=True, max_length=20, verbose_name='Kategória')),
                ('action', models.CharField(choices=[('create', 'Létrehozás'), ('update', 'Módosítás'), ('delete', 'Törlés'), ('login', 'Bejelentkezés'), ('logout', 'Kijelentkezés'), ('login_failed', 'Sikertelen bejelentkezés'), ('view', 'Megtekintés'), ('send', 'Küldés'), ('accept', 'Elfogadás'), ('reject', 'Elutasítás'), ('cancel', 'Lemondás'), ('export', 'Exportálás'), ('upload', 'Feltöltés'), ('download', 'Letöltés'), ('publish', 'Közzététel'), ('draft', 'Piszkozat mentés'), ('password_reset', 'Jelszó visszaállítás'), ('password_change', 'Jelszó változtatás')], db_index=True, max_length=20, verbose_name='Művelet')),
                ('object_type', models.CharField(blank=True, max_length=100, verbose_name='Objektum típus')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Objektum ID')),
                ('object_repr', models.CharField(blank=True, max_length=200, verbose_name='Objektum neve')),
                ('description', models.TextField(verbose_name='Leírás')),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='Változások')),
                ('extra_data', models.JSONField(blank=True, null=True, verbose_name='Extra adatok')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Felhasználó')),
            ],
            options={
                'verbose_name': 'Napló bejegyzés',
                'verbose_name_plural': 'Napló bejegyzések',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['category', 'timestamp'], name='audit_audit_categor_c661fd_idx'), models.Index(fields=['user', 'timestamp'], name='audit_audit_user_id_e8be02_idx'), models.Index(fields=['action', 'timestamp'], name='audit_audit_action_2a1328_idx'), models.Index(fields=['object_type', 'object_id'], name='audit_audit_object__1f9df3_idx')],
            },
        ),
    ]
